// <auto-generated />
namespace SatoImsV1._1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class sept29_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sept29_update));
        
        string IMigrationMetadata.Id
        {
            get { return "202009290321021_sept29_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
