// <auto-generated />
namespace SatoImsV1._1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class change_to_rowver_receiving : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_to_rowver_receiving));
        
        string IMigrationMetadata.Id
        {
            get { return "202006210651433_change_to_rowver_receiving"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
